Contacts/urls.py
from django.urls import path
from . import views


app_name = 'contact'

urlpatterns = [
    path('',views.index,name='index'),
    path('search_page=<int:page>',views.index,name='index'),
    path("search/",views.search_contact,name="search"),
    path('contact/<int:contact_id>',views.view_contact,name='view_contact'),
    path('contact/edit_contact/<int:contact_id>',views.edit_contact,name='edit_contact'),
    path('contact/create_contact',views.create_contact,name='create_contact'),
    path('contact/delete_contact/<int:contact_id>',views.delete_contact_view,name='delete_contact'),
]

MeusContatos/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('Contacts.urls')),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Contacts/models.py
from typing import Any
from django.db import models

# Create your models here.

class Contact(models.Model):

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)

    primeiro_nome = models.CharField(max_length=50,verbose_name='Primeiro nome')
    ultimo_nome = models.CharField(max_length=50,verbose_name='Ultimo nome',blank=True)
    email = models.EmailField(unique=True,blank=True,)
    description = models.TextField(verbose_name="descrição",blank=True)
    celular = models.CharField(blank=True,max_length=14)
    show = models.BooleanField(default=False)
    picture = models.ImageField(verbose_name="imagem",blank=True,upload_to="image/")

    def __str__(self):
        return self.primeiro_nome
    

Contacts/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ("primeiro_nome","ultimo_nome","email","celular","description","picture")

Contacts/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Contact
from django.core.paginator import Paginator
from .forms import ContactForm
from utils.handle_upload_image import handle_uploaded_file
from datetime import datetime
from .utils.initial_data_form import set_initial_data
from django.urls import reverse
from django.db.models import Q

# Create your views here.
def index(request,page=1):    
    contacts = Contact.objects.all()
    paginator = Paginator(contacts,10)
    deleted=False
    try:
        deleted = request.GET["contact"]
    except:
        ...
    if deleted==False:
        context = {
            'contacts':paginator.page(page),
            'paginator':paginator
        }
    else:
        context = {
            'contacts':paginator.page(page),
            'paginator':paginator,
            'message':"Contato deletado com sucesso"
        }
    return render(request,'contacts/index.html',context)

def search_contact(request):
    nome = request.GET.get("name")
    page = int(request.GET.get("page"))
    contacts = Contact.objects.filter(Q(primeiro_nome__icontains=nome)|Q(ultimo_nome__icontains=nome))
    paginator = Paginator(contacts,10)
    return render(request,'contacts/search.html',{
        'contacts':paginator.page(page),
        'paginator':paginator,
        'name':nome

    })


def view_contact(request,contact_id):
    contact = get_object_or_404(Contact,pk=contact_id)
    return render(request,'contacts/view_contact.html',{
        'contact':contact,
    })
 
def edit_contact(request,contact_id):
    contact = get_object_or_404(Contact,pk=contact_id)
    try:
        dados_iniciais={
            'primeiro_nome':contact.primeiro_nome,
            'ultimo_nome':contact.ultimo_nome,
            'email':contact.email,
            'celular':contact.celular,
            'description':contact.description,
            'picture':contact.picture.url

        }
    except:
        dados_iniciais={
            'primeiro_nome':contact.primeiro_nome,
            'ultimo_nome':contact.ultimo_nome,
            'email':contact.email,
            'celular':contact.celular,
            'description':contact.description,
        }
    if request.method == "POST":
        form = ContactForm(request.POST,request.FILES,instance=contact)
        
        if form.is_valid():
            contact=form.save(commit=False)
            contact.save()
            form = ContactForm(initial=set_initial_data(contact))
            return render(request,'contacts/edit_contact.html',
            {
                'message':"Contato editado com sucesso",
                'form':form,
                'contact_picture_url':contact.picture,
                'contact_id':contact.pk
            })
        else:
            return render(request,'contacts/edit_contact.html',
            {
                'message':"Corrija o erros",
                'form':form,
                'contact_picture_url':contact.picture,
                'contact_id':contact.pk
            })
    else:
        form = ContactForm(initial=dados_iniciais)
        return render(request,'contacts/edit_contact.html',{
            'form':form,
            'contact_picture_url':contact.picture,
            'contact_id':contact.pk
        })
    
def create_contact(request):
    
    if request.method == "POST":
        form = ContactForm(request.POST,request.FILES)
        
        if form.is_valid():
            contact=form.save(commit=False)
            contact.save()
            form = ContactForm(initial=set_initial_data(contact))
            return render(request,'contacts/create_contact.html',
            {
                'message':"Contato editado com sucesso",
                'form':form,
                'contact_picture_url':contact.picture,
            })
        else:
            return render(request,'contacts/create_contact.html',
            {
                'message':"Corrija o erros",
                'form':form,
            })
    else:
        form = ContactForm()
        return render(request,'contacts/create_contact.html',{
            'form':form,
        })
    
def delete_contact_view(request,contact_id):
    contact = get_object_or_404(Contact,pk=contact_id)
    delete = False
    try:
        delete = request.GET['delete']
    except:
        ...
    if delete == False:
        return render(request,'contacts/view_contact.html',{
            "show_exclude":True,
            "contact":contact
        })
    else:
        contact.delete()
        base_url = reverse('contact:index')
        query="contact=deleted"
        url = f"{base_url}?{query}"
        return redirect(url)

Contacts/templates/contacts/create_contact.html
{% extends 'html/base.html' %}
{% block content %}
<div class="container">
<h1 class="title">
    <a href="{% url 'contact:index' %}">Agenda</a>
</h1>
<a class="create-contact" href="{% url 'contact:create_contact' %}">Criar</a>
{% if message %}
<h3 class="form-message">{{message}}</h3>
{% endif %}
    <form class="edit_contact" action="" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <div class="input-info">
            {{ form.primeiro_nome.errors }}
            <label for="{{ form.primeiro_nome.id_for_label }}">{{form.primeiro_nome.label}}</label>
            {{ form.primeiro_nome }}
        </div>
        <div class="input-info">
            {{ form.ultimo_nome.errors }}
            <label for="{{ form.ultimo_nome.id_for_label }}">{{form.ultimo_nome.label}}</label>
            {{ form.ultimo_nome }}
        </div>
        <div class="input-info">
            {{ form.email.errors }}
            <label for="{{ form.email.id_for_label }}">{{form.email.label}}</label>
            {{ form.email }}
        </div>
        <div class="input-info">
            {{ form.celular.errors }}
            <label for="{{ form.celular.id_for_label }}">{{form.celular.label}}</label>
            {{ form.celular }}
        </div>
        <div class="input-info">
            {{ form.description.errors }}
            <label for="{{ form.description.id_for_label }}">{{form.description.label}}</label>
            {{ form.description }}
        </div>
        <div class="input-info">
            {{ form.picture.errors }}
            <label for="{{ form.picture.id_for_label }}">{{form.picture.label}}</label>
            {{ form.picture }}
        </div>
        {% if contact_picture_url %}
            <div class="input-info">
                <label>Imagem atual</label>
                <img src="{{contact_picture_url.url}}" width="300" alt="">
            </div>
        {% endif %}
        <div class="input-info">
            <input type="submit" value="Submit">
        </div>
    </form>
</div>
{% endblock content %}

Contacts/templates/contacts/edit_contact.html
{% extends 'html/base.html' %}
{% block content %}
<div class="container">
<h1 class="title">
    <a href="{% url 'contact:index' %}">Agenda</a>
</h1>
<a class="create-contact" href="{% url 'contact:create_contact' %}">Criar</a>
<a class="back-view-contact" href="{% url 'contact:view_contact' contact_id %}">Voltar</a>
{% if message %}
<h3 class="form-message">{{message}}</h3>
{% endif %}
    <form class="edit_contact" action="" enctype="multipart/form-data" method="post">
        {% csrf_token %}
        <div class="input-info">
            {{ form.primeiro_nome.errors }}
            <label for="{{ form.primeiro_nome.id_for_label }}">{{form.primeiro_nome.label}}</label>
            {{ form.primeiro_nome }}
        </div>
        <div class="input-info">
            {{ form.ultimo_nome.errors }}
            <label for="{{ form.ultimo_nome.id_for_label }}">{{form.ultimo_nome.label}}</label>
            {{ form.ultimo_nome }}
        </div>
        <div class="input-info">
            {{ form.email.errors }}
            <label for="{{ form.email.id_for_label }}">{{form.email.label}}</label>
            {{ form.email }}
        </div>
        <div class="input-info">
            {{ form.celular.errors }}
            <label for="{{ form.celular.id_for_label }}">{{form.celular.label}}</label>
            {{ form.celular }}
        </div>
        <div class="input-info">
            {{ form.description.errors }}
            <label for="{{ form.description.id_for_label }}">{{form.description.label}}</label>
            {{ form.description }}
        </div>
        <div class="input-info">
            {{ form.picture.errors }}
            <label for="{{ form.picture.id_for_label }}">{{form.picture.label}}</label>
            {{ form.picture }}
        </div>
        {% if contact_picture_url %}
            <div class="input-info">
                <label>Imagem atual</label>
                <img src="{{contact_picture_url.url}}" width="300" alt="">
            </div>
        {% endif %}
        <div class="input-info">
            <input type="submit" value="Submit">
        </div>
    </form>
</div>
{% endblock content %}

Contacts/templates/contacts/index.html
{% extends 'html/base.html' %}
{% block content %}
    <div class="container">
        <h1 class="title">
            <a href="{% url 'contact:index' %}">Agenda</a>
        </h1>
        <h4 class="title">{{message}}</h4>
        <form class="title" style="width: 30%; text-align: center;" action="" method="POST">
            {% csrf_token %}
            <input style="width: 70%;height: 20px;padding: 5px;" type="text" name="name" placeholder="Consulte por nome">
            <input style="width: 20%;height: 30px;padding: 5px;" type="submit" value="Pesquisar">
        </form>
        <a class="create-contact" href="{% url 'contact:create_contact' %}">Criar</a>
        <div class="contact-info">
            <p>id</p>
            <p>nome</p>
            <p>email</p>
            <p>celular</p>
        </div>
        {% for contact in contacts %}
        <div class="contact-info">
                <p>
                    <a href="{% url 'contact:view_contact' contact.pk %}">{{contact.pk}}</a>
                </p>
                <p>{{contact.primeiro_nome}} {{contact.ultimo_nome}}</p>
                <p>{{contact.email}}</p>
                <p>{{contact.celular}}</p>
        </div>
        {%endfor%}
        {% if contacts.has_previous %}
            <a  class="previous-btn" href="{% url 'contact:index' contacts.previous_page_number %}">anterior</a>
        {% else %}
            <a class="previous-btn" href="">anterior</a>
        {% endif%}
        {% if contacts.has_next %}
            <a class="next-btn" href="{% url 'contact:index' contacts.next_page_number %}">proximo</a>
        {% else %}
            <a class="next-btn" href="">proximo</a>
        {% endif%}
    </div>
{% endblock content %}

Contacts/templates/contacts/search.html
{% extends 'html/base.html' %}
{% block content %}
    <div class="container">
        <h1 class="title">
            <a href="{% url 'contact:index' %}">Agenda</a>
        </h1>
        <h4 class="title">{{message}}</h4>
        <form class="title" style="width: 30%; text-align: center;" action="{% url 'contact:search' %}" method="GET">
            <input style="width: 70%;height: 20px;padding: 5px;" type="text" name="name" placeholder="Consulte por nome" value="{{name}}">
            <input type="hidden" name="page" value="1">
            <input style="width: 20%;height: 30px;padding: 5px;" type="submit" value="Pesquisar">
        </form>
        <a class="create-contact" href="{% url 'contact:create_contact' %}">Criar</a>
        <div class="contact-info">
            <p>id</p>
            <p>nome</p>
            <p>email</p>
            <p>celular</p>
        </div>
        {% for contact in contacts %}
        <div class="contact-info">
                <p>
                    <a href="{% url 'contact:view_contact' contact.pk %}">{{contact.pk}}</a>
                </p>
                <p>{{contact.primeiro_nome}} {{contact.ultimo_nome}}</p>
                <p>{{contact.email}}</p>
                <p>{{contact.celular}}</p>
        </div>
        {%endfor%}
        {% if contacts.has_previous %}
            <a  class="previous-btn" href="{{request.path}}?name={{name}}&page={{contacts.previous_page_number}}">anterior</a>
        {% else %}
            <a class="previous-btn" href="">anterior</a>
        {% endif%}
        {% if contacts.has_next %}
            <a  class="next-btn" href="{{request.path}}?name={{name}}&page={{contacts.next_page_number}}">Proximo</a>
        {% else %}
            <a class="next-btn" href="">proximo</a>
        {% endif%}
    </div>
{% endblock content %}

Contacts/templates/contacts/view_contact.html
{% extends 'html/base.html' %}
{% block content %}
    <div class="container">
        <h1 class="title">
            <a href="{% url 'contact:index' %}">Agenda</a>
        </h1>
        <a class="create-contact" href="{% url 'contact:create_contact' %}">Criar</a>
        <div class="contact-container">
            <p><b>Nome completo:</b> {{contact.primeiro_nome}} {{contact.ultimo_nome}}</p>
            <p><b>Email:</b> {{contact.email}}</p>
            <p><b>Celular</b> {{contact.celular}}</p>
            <p><b>Descrição</b> {{contact.description}}</p>
            {% if contact.picture %}
            <img src="{{contact.picture.url}}" width="300" alt="">
            {% endif %}
            <div class="link-items">
                <a href="{% url 'contact:edit_contact' contact.pk %}">Editar</a>
                {% if show_exclude %}
                    <a href="{% url 'contact:delete_contact' contact.pk %}?delete=confirm">Tem certeza?</a>
                {% else %}
                    <a href="{% url 'contact:delete_contact' contact.pk %}">Excluir</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}